version: "3.9"  # optional since v1.27.0
services:
  api-ebilling:
    image: php8server:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./logs:/var/log
